name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}

version: ${project.version}
api-version: 1.16

author: Cable

commands:
  cablecorners:
    aliases: [ cc, ccorners ]
    permission: cablecorners.admin
