name: CableCorners
main: me.cable.corners.CableCorners

version: ${project.version}
api-version: 1.16

author: Cable

commands:
  cablecorners:
    aliases: [ cc, ccorners ]
    permission: cablecorners.command.cablecorners
